services:
  backend:
    build:
      context: .
    network_mode: "host"  
    environment:
      - BASE_IP=${BASE_IP}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
